CREATE TABLE `Plantilla_json_api` (
  `id_json_api` int NOT NULL AUTO_INCREMENT COMMENT 'identificador',
  `orden` int DEFAULT '0' COMMENT 'orden de ejecución',
  `tipo_api` varchar(20) COLLATE utf8mb4_spanish_ci DEFAULT '' COMMENT 'tipo de api',
  `api_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL COMMENT 'nombre de api ewp',
  `date_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'feha de creación',
  `version_json` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL COMMENT 'versión de la plantilla del api',
  `status_json` tinyint NOT NULL COMMENT 'estado de activación',
  `type_token` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci NOT NULL COMMENT 'tipo de token a utilizar en el api : "admin", "msisdn"',
  `is_blacklist` tinyint DEFAULT NULL,
  PRIMARY KEY (`id_json_api`),
  KEY `idx_plantilla_api_name` (`api_name`),
  KEY `idx_plantilla_status_json` (`status_json`),
  KEY `idx_plantilla_id_json_api` (`id_json_api`),
  KEY `idx_plantilla_api_name_status_json` (`api_name`,`status_json`),
  KEY `idx_d_composite` (`id_json_api`,`tipo_api`,`orden`)
) ENGINE=InnoDB AUTO_INCREMENT=85 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci

INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (1, 2, 'consulta', 'getbalance', '2024-09-27 17:14:10', 'general', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (2, 0, '', 'getaccountholderemail', '2024-09-28 19:10:50', 'general', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (3, 3, 'consulta', 'gettransactionhistory', '2024-09-30 18:43:42', 'general', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (4, 0, '', 'getaccountholderidentification', '2024-09-30 18:43:42', 'general', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (5, 1, 'usuario', 'registration', '2024-09-30 18:43:42', 'general', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (6, 0, '', 'getaccountholderpersonalinformation', '2024-09-30 18:43:42', 'general', 1, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (7, 0, '', 'getaccounts', '2024-09-30 18:43:42', 'general', 1, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (8, 1, 'consulta', 'getaccountholderinfo', '2024-09-30 18:43:42', 'general', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (9, 0, '', 'getaccountholdersbyidentification', '2024-09-30 18:43:42', 'general', 1, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (10, 0, '', 'setaccountprofile', '2024-09-30 18:43:42', 'general', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (11, 0, '', 'setemail', '2024-09-30 18:43:42', 'general', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (12, 0, '', 'sethomechargingregion', '2024-09-30 18:43:42', 'general', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (13, 0, '', 'setmsisdn', '2024-09-30 18:43:42', 'general', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (14, 0, '', 'updateaccountholderaddress', '2024-09-30 18:43:42', 'general', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (15, 0, '', 'updateaccountholderidentification', '2024-09-30 18:43:42', 'general', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (16, 0, '', 'updateaccountholderpersonalinformation', '2024-09-30 18:43:42', 'reniec', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (17, 2, 'usuario', 'activation', '2024-09-30 18:43:42', 'general', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (18, 0, '', 'adjustment', '2024-09-30 18:43:42', 'general', 0, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (19, 1, 'transaccion', 'cashin', '2024-09-30 18:43:42', 'VIRTUALINTEROPCFBIM', 1, 'agente', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (20, 6, 'transaccion', 'cashout', '2024-09-30 18:43:42', 'general', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (21, 9999, 'consulta', 'cashout/quote', '2024-09-30 18:43:42', 'general', 0, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (22, 9999, 'consulta', 'merchantpayment/quote', '2024-09-30 18:43:42', 'wu', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (24, 9999, 'consulta', 'transfer/quote', '2024-09-30 18:43:42', 'general', 1, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (25, 0, '', 'closeaccount', '2024-09-30 18:43:42', 'general', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (26, 0, '', 'closeaccountholder', '2024-09-30 18:43:42', 'general', 1, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (27, 0, '', 'getapprovals', '2024-09-30 18:43:42', 'general', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (28, 0, '', 'gettransactionhistory2', '2024-09-30 18:43:42', 'id', 1, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (29, 0, '', 'initiatepinreset', '2024-09-30 18:43:42', 'general', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (31, 8, 'transaccion', 'merchantpayment', '2024-09-30 18:43:42', 'COMPW0165', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (32, 9999, 'transaccion', 'payment', '2024-09-30 18:43:42', 'wu', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (33, 100, 'transaccion', 'refund', '2024-09-30 18:43:42', 'azulito', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (34, 2, 'transaccion', 'transfer', '2024-09-30 18:43:42', 'general', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (35, 0, '', 'resetcredentialwithotp', '2024-09-30 18:43:42', 'general', 1, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (36, 0, '', 'updatecredential', '2024-09-30 18:43:42', 'general', 1, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (37, 100, 'transaccion', 'reversetransaction', '2024-09-30 18:43:42', 'cashout', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (38, 0, '', 'getreversetransactiondetails', '2024-09-30 18:43:42', 'general', 1, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (39, 0, '', 'transfertoanybankaccount', '2024-09-30 18:43:42', 'general', 1, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (40, 0, '', 'setprofile', '2024-09-30 18:43:42', 'general', 1, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (48, 11, 'transaccion', 'payment', '2024-09-30 18:43:42', 'azulito', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (49, 14, 'transaccion', 'payment', '2024-09-30 18:43:42', 'bitel', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (50, 12, 'transaccion', 'payment', '2024-09-30 18:43:42', 'unique', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (51, 17, 'transaccion', 'payment', '2024-09-30 18:43:42', 'claro', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (52, 13, 'transaccion', 'payment', '2024-09-30 18:43:42', 'sunat', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (53, 9999, 'transaccion', 'payment', '2024-09-30 18:43:42', 'gmoney', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (54, 16, 'transaccion', 'payment', '2024-09-30 18:43:42', 'airtimebitel', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (55, 1, 'transaccion', 'cashin', '2024-09-30 18:43:42', 'VIRTUALINTEROPCFCCE', 1, 'agente', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (56, 9999, 'transaccion', 'bnacion_ofi_ci/cashin', '2024-09-30 18:43:42', 'AgenteBNacion', 1, 'agente', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (57, 1, 'transaccion', 'cashin', '2024-09-30 18:43:42', 'COMPWVIRTUAL163', 1, 'agente', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (58, 1, 'transaccion', 'cashin', '2024-09-30 18:43:42', 'COMPWKASNET', 1, 'agente', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (59, 9999, 'transaccion', 'atmcashout', '2024-09-30 18:43:42', 'atmcompartamos', 1, 'agente', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (60, 9999, 'consulta', 'payment/quote', '2024-09-30 18:43:42', 'azulito', 1, 'admin', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (61, 9999, 'consulta', 'payment/quote', '2024-09-30 18:43:42', 'bitel', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (62, 9999, 'consulta', 'payment/quote', '2024-09-30 18:43:42', 'unique', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (63, 9999, 'consulta', 'payment/quote', '2024-09-30 18:43:42', 'claro', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (64, 9999, 'consulta', 'payment/quote', '2024-09-30 18:43:42', 'sunat', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (65, 9999, 'consulta', 'payment/quote', '2024-09-30 18:43:42', 'airtime', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (66, 0, '', 'getaccountholderaddress', '2024-09-30 18:43:42', 'general', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (67, 9999, 'transaccion', 'payment', '2024-09-30 18:43:42', 'backus', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (68, 0, '', 'getbalance', '2024-09-27 17:14:10', 'auth', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (69, 9999, 'transaccion', 'refund', '2024-09-30 18:43:42', 'wu', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (70, 0, '', 'updateaccountholderpersonalinformation', '2024-09-30 18:43:42', 'wu', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (71, 0, '', 'updateaccountholderpersonalinformation', '2024-09-30 18:43:42', 'nombre', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (72, 0, '', 'updateaccountholderpersonalinformation', '2024-09-30 18:43:42', 'emisor', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (73, 100, 'transaccion', 'reversetransaction', '2024-09-30 18:43:42', 'cashin', 1, 'agente', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (74, 9999, 'transaccion', 'atmcashout', '2024-09-30 18:43:42', 'atmfullcargas', 1, 'agente', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (75, 9999, 'transaccion', 'refund', '2024-09-30 18:43:42', 'backus', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (76, 9999, 'transaccion', 'refund', '2024-09-30 18:43:42', 'pmpcompras', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (77, 9999, 'transaccion', 'payment', '2024-09-30 18:43:42', 'pmpcompras', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (78, 100, 'transaccion', 'transfer', '2024-09-30 18:43:42', 'refund', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (79, 0, '', 'getbalancedelete', '2024-09-27 17:14:10', 'general', 1, 'none', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (80, 1, 'transaccion', 'cashin', '2024-09-30 18:43:42', 'COMPWFULLCARGA', 1, 'agente', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (81, 9, 'transaccion', 'merchantpayment', '2024-09-30 18:43:42', 'COMPW0086', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (82, 10, 'transaccion', 'merchantpayment', '2024-09-30 18:43:42', 'CRAPW0061', 1, 'msisdn', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (83, 9999, 'transaccion', 'cashin', '2024-09-30 18:43:42', 'COMPWGOPAY', 1, 'agente', 0);
INSERT INTO DRYRUN_CAPTURE.Plantilla_json_api (id_json_api, orden, tipo_api, api_name, date_created, version_json, status_json, type_token, is_blacklist) VALUES (84, 15, 'transaccion', 'payment', '2024-09-30 18:43:42', 'airtimemovistar', 1, 'msisdn', 0);
